### PR TITLE
Fix http urls

### PR DESCRIPTION
**Pull request by alvassin**
Removed ssl checks for http urls

### CODE REVIEW

**Comment by cassianoleal** [comment]
Sorry, but I fail to understand why you'd want to use insecure SSL.
I certainly don't want my automation software blindly accepting any home baked certs and MITMs out there.

**Comment by alvassin** [comment]
@cassianoleal if you don't want to - use https urls. Why not?

**Comment by cassianoleal** [comment]
@alvassin I'm terribly sorry, I misread your code completely.

I'm not on the computer right now but I'll give it a second look when I am.

Just so I understand, why is that `if` necessary? What fails without it?

**Comment by cassianoleal** [comment]
Ok, got it. I guess I had never tested this with plain HTTP.

Thanks for this pull request!

**Comment by alvassin** [comment]
Thanks a lot, @cassianoleal. Much appreciated.

**Comment by cassianoleal** [comment]
No worries! I've published a point release 2.0.1 with this fix. Cheers! :beers:

**Pull request merged**
